import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import multer from 'multer';
import dotenv from 'dotenv';
import pg from 'pg';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import crypto from 'crypto';
import { spawn } from 'child_process';
import fs from 'fs/promises';
import os from 'os';
import path from 'path';

dotenv.config();
const app = express();
const { Pool } = pg;
const PORT = process.env.PORT || 10000;
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.DATABASE_SSL === 'false' ? false : { rejectUnauthorized: false }
});
app.use(helmet({ crossOriginResourcePolicy: false }));
app.use(cors({ origin: process.env.FRONTEND_ORIGIN || '*' }));
app.use(express.json({ limit: '2mb' }));
app.use(morgan('combined'));
const upload = multer({ dest: path.join(os.tmpdir(), 'adamovies'), limits: { fileSize: Number(process.env.MAX_UPLOAD_BYTES || 20 * 1024 * 1024 * 1024) } });

function signUser(user) { return jwt.sign({ sub:user.id, role:user.role, email:user.email }, process.env.JWT_SECRET, { expiresIn:'7d' }); }
async function auth(req,res,next){ try { const h=req.headers.authorization||''; if(!h.startsWith('Bearer ')) return res.status(401).json({error:'Authentication required'}); const p=jwt.verify(h.slice(7),process.env.JWT_SECRET); const {rows}=await pool.query('SELECT id,email,display_name,role,created_at FROM users WHERE id=$1',[p.sub]); if(!rows[0]) return res.status(401).json({error:'User not found'}); req.user=rows[0]; next(); } catch { res.status(401).json({error:'Invalid or expired token'}); } }
function requireRole(...roles){ return (req,res,next)=>roles.includes(req.user?.role)?next():res.status(403).json({error:'Insufficient permissions'}); }
async function tmdb(endpoint,params={}){ if(!process.env.TMDB_API_KEY) throw new Error('TMDB_API_KEY is not configured'); const u=new URL(`https://api.themoviedb.org/3${endpoint}`); u.searchParams.set('api_key',process.env.TMDB_API_KEY); for(const [k,v] of Object.entries(params)) if(v!=null) u.searchParams.set(k,String(v)); const r=await fetch(u); const d=await r.json(); if(!r.ok) throw new Error(d.status_message||`TMDB error ${r.status}`); return d; }
function getDuration(file){ return new Promise((resolve,reject)=>{ const p=spawn(process.env.FFPROBE_PATH||'ffprobe',['-v','error','-show_entries','format=duration','-of','default=noprint_wrappers=1:nokey=1',file]); let out='',err=''; p.stdout.on('data',d=>out+=d); p.stderr.on('data',d=>err+=d); p.on('error',reject); p.on('close',code=>{ const n=Number.parseFloat(out.trim()); if(code!==0||!Number.isFinite(n)) return reject(new Error(err||'ffprobe failed')); resolve(n); }); }); }
function runtimeMatches(actualSeconds,tmdbMinutes){ const min=Number(process.env.MIN_RUNTIME_MINUTES||90), tol=Number(process.env.RUNTIME_TOLERANCE_MINUTES||3); return actualSeconds>=min*60 && Math.abs(actualSeconds-Number(tmdbMinutes)*60)<=tol*60; }

app.get('/api/health',async(_req,res)=>{ try{await pool.query('SELECT 1');res.json({status:'ok',service:'adamovies-backend',database:'connected'});}catch{res.status(503).json({status:'error',database:'unavailable'});} });
app.post('/api/auth/register',async(req,res)=>{const {email,password,displayName}=req.body||{}; if(!email||!password||password.length<8)return res.status(400).json({error:'Email and password of at least 8 characters are required'}); try{const hash=await bcrypt.hash(password,12);const {rows}=await pool.query(`INSERT INTO users(email,password_hash,display_name) VALUES($1,$2,$3) RETURNING id,email,display_name,role,created_at`,[email.toLowerCase().trim(),hash,displayName||'ADAMOVIES User']);res.status(201).json({user:rows[0],token:signUser(rows[0]),free_period_until:new Date(Date.now()+86400000).toISOString()});}catch(e){if(e.code==='23505')return res.status(409).json({error:'Email already registered'});res.status(500).json({error:'Registration failed'});} });
app.post('/api/auth/login',async(req,res)=>{const email=(req.body?.email||'').toLowerCase().trim(),password=req.body?.password||'';const {rows}=await pool.query('SELECT * FROM users WHERE email=$1',[email]);const user=rows[0];if(!user||!(await bcrypt.compare(password,user.password_hash)))return res.status(401).json({error:'Invalid email or password'});res.json({token:signUser(user),user:{id:user.id,email:user.email,display_name:user.display_name,role:user.role,created_at:user.created_at}});});
app.get('/api/me',auth,async(req,res)=>{const {rows}=await pool.query(`SELECT id,email,display_name,role,created_at,download_credits,created_at+interval '24 hours'>NOW() AS free_period_active FROM users WHERE id=$1`,[req.user.id]);res.json(rows[0]);});
app.get('/api/tmdb/search',auth,requireRole('admin','super_admin'),async(req,res)=>{try{const d=await tmdb('/search/movie',{query:req.query.q,include_adult:false,language:'en-US'});res.json(d.results||[]);}catch(e){res.status(502).json({error:e.message});}});
app.get('/api/tmdb/movie/:id',auth,requireRole('admin','super_admin'),async(req,res)=>{try{res.json(await tmdb(`/movie/${req.params.id}`,{append_to_response:'credits'}));}catch(e){res.status(502).json({error:e.message});}});
app.post('/api/admin/movies/upload',auth,requireRole('admin','super_admin'),upload.single('video'),async(req,res)=>{let tempFile;try{if(!req.file)return res.status(400).json({error:'Video file is required'});const tmdbId=Number(req.body.tmdbId);if(!tmdbId)return res.status(400).json({error:'tmdbId is required'});const movie=await tmdb(`/movie/${tmdbId}`,{append_to_response:'credits'});const minimum=Number(process.env.MIN_RUNTIME_MINUTES||90);if(!movie.runtime||movie.runtime<minimum)return res.status(400).json({error:`TMDB runtime must be at least ${minimum} minutes`});tempFile=req.file.path;const actualSeconds=await getDuration(tempFile);if(!runtimeMatches(actualSeconds,movie.runtime))return res.status(400).json({error:'Uploaded video runtime does not sufficiently match TMDB runtime',tmdb_runtime_minutes:movie.runtime,uploaded_runtime_minutes:Math.round(actualSeconds/60*100)/100,tolerance_minutes:Number(process.env.RUNTIME_TOLERANCE_MINUTES||3)});const muxPlaybackId=req.body.muxPlaybackId;if(!muxPlaybackId)return res.status(400).json({error:'muxPlaybackId is required'});const genres=(movie.genres||[]).map(g=>g.name);const cast=(movie.credits?.cast||[]).slice(0,20).map(p=>({id:p.id,name:p.name,character:p.character,profile_path:p.profile_path?`https://image.tmdb.org/t/p/w185${p.profile_path}`:null}));const {rows}=await pool.query(`INSERT INTO movies(tmdb_id,title,overview,release_date,poster_path,backdrop_path,runtime_minutes,tmdb_rating,genres,cast_json,mux_playback_id,status,uploaded_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'published',$12) RETURNING *`,[movie.id,movie.title,movie.overview||'',movie.release_date||null,movie.poster_path?`https://image.tmdb.org/t/p/w500${movie.poster_path}`:null,movie.backdrop_path?`https://image.tmdb.org/t/p/w1280${movie.backdrop_path}`:null,movie.runtime,movie.vote_average||null,genres,JSON.stringify(cast),muxPlaybackId,req.user.id]);res.status(201).json({movie:rows[0],verified_runtime_seconds:actualSeconds});}catch(e){res.status(500).json({error:e.message||'Upload failed'});}finally{if(tempFile)fs.unlink(tempFile).catch(()=>{});}});
app.get('/api/movies',async(req,res)=>{const limit=Math.min(Number(req.query.limit||50),100),offset=Math.max(Number(req.query.offset||0),0);const {rows}=await pool.query(`SELECT * FROM movies WHERE status='published' ORDER BY created_at DESC LIMIT $1 OFFSET $2`,[limit,offset]);res.json(rows);});
app.get('/api/movies/:id',async(req,res)=>{const {rows}=await pool.query(`SELECT * FROM movies WHERE id=$1 AND status='published'`,[req.params.id]);if(!rows[0])return res.status(404).json({error:'Movie not found'});res.json(rows[0]);});
app.get('/api/trending',async(_req,res)=>{const {rows}=await pool.query(`SELECT m.*,t.position FROM trending_movies t JOIN movies m ON m.id=t.movie_id WHERE m.status='published' ORDER BY t.position`);res.json(rows);});
app.post('/api/admin/trending',auth,requireRole('super_admin'),async(req,res)=>{const {movieId,position=0}=req.body||{};await pool.query(`INSERT INTO trending_movies(movie_id,position,added_by) VALUES($1,$2,$3) ON CONFLICT(movie_id) DO UPDATE SET position=EXCLUDED.position,added_by=EXCLUDED.added_by`,[movieId,position,req.user.id]);res.json({ok:true});});
app.delete('/api/admin/trending/:movieId',auth,requireRole('super_admin'),async(req,res)=>{await pool.query('DELETE FROM trending_movies WHERE movie_id=$1',[req.params.movieId]);res.json({ok:true});});
app.get('/api/admin/movies',auth,requireRole('admin','super_admin'),async(_req,res)=>{const {rows}=await pool.query('SELECT * FROM movies ORDER BY created_at DESC');res.json(rows);});
app.delete('/api/admin/movies/:id',auth,requireRole('super_admin'),async(req,res)=>{await pool.query(`UPDATE movies SET status='deleted' WHERE id=$1`,[req.params.id]);res.json({ok:true});});
app.post('/api/download/authorize',auth,async(req,res)=>{const movieId=Number(req.body?.movieId);if(!movieId)return res.status(400).json({error:'movieId is required'});const client=await pool.connect();try{await client.query('BEGIN');const {rows:movies}=await client.query(`SELECT id,title,mux_playback_id FROM movies WHERE id=$1 AND status='published' FOR SHARE`,[movieId]);if(!movies[0])throw new Error('Movie not found');const {rows:users}=await client.query(`SELECT id,download_credits,created_at FROM users WHERE id=$1 FOR UPDATE`,[req.user.id]);const user=users[0];const free=new Date(user.created_at).getTime()+86400000>Date.now();if(!free&&user.download_credits<1){await client.query('ROLLBACK');return res.status(402).json({error:'No download credits. Watch a rewarded ad or buy coins.',free_period_active:false});}if(!free){await client.query('UPDATE users SET download_credits=download_credits-1 WHERE id=$1',[user.id]);await client.query(`INSERT INTO credit_ledger(user_id,kind,amount,reason) VALUES($1,'debit',-1,$2)`,[user.id,`Movie download: ${movieId}`]);}await client.query(`INSERT INTO downloads(user_id,movie_id,used_free_period,credits_spent) VALUES($1,$2,$3,$4)`,[user.id,movieId,free,free?0:1]);await client.query('COMMIT');res.json({ok:true,download_authorized:true,consumed_credit:!free,movie:movies[0]});}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message});}finally{client.release();}});
app.post('/api/rewards/grant',async(req,res)=>{const signature=req.headers['x-adamovies-signature'],secret=process.env.REWARD_WEBHOOK_SECRET;if(!secret||!signature)return res.status(401).json({error:'Reward verification is not configured'});const expected=crypto.createHmac('sha256',secret).update(JSON.stringify(req.body)).digest('hex'),provided=String(signature);if(provided.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(provided),Buffer.from(expected)))return res.status(401).json({error:'Invalid reward signature'});const {userId,rewardId}=req.body||{};if(!userId||!rewardId)return res.status(400).json({error:'userId and rewardId are required'});const client=await pool.connect();try{await client.query('BEGIN');const inserted=await client.query(`INSERT INTO ad_rewards(user_id,reward_id) VALUES($1,$2) ON CONFLICT(reward_id) DO NOTHING RETURNING id`,[userId,rewardId]);if(inserted.rowCount){await client.query('UPDATE users SET download_credits=download_credits+5 WHERE id=$1',[userId]);await client.query(`INSERT INTO credit_ledger(user_id,kind,amount,reason) VALUES($1,'credit',5,'Completed rewarded ad')`,[userId]);}await client.query('COMMIT');res.json({ok:true,granted:Boolean(inserted.rowCount),credits:5});}catch(e){await client.query('ROLLBACK');res.status(500).json({error:e.message});}finally{client.release();}});
app.post('/api/coins/credit',auth,async(_req,res)=>res.status(405).json({error:'Coins must be granted by a verified payment webhook'}));
app.listen(PORT,()=>console.log(`ADAMOVIES backend running on port ${PORT}`));
